name: Upload to Google Drive

on:
  push:
    branches:
      - main 

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Upload calcs folder
        uses: Jodebu/upload-to-drive@v1
        with:
          credentials: ${{ secrets.GOOGLE_DRIVE_CREDENTIALS }}
          folder: 1AE0EvqMRu7_45NQhOC3VbkpS2q-2o3Jc # The source folder in your repository
          target: calcs   # The destination folder name in Google Drive

