name: Upload to Google Drive

on:
  push:
    branches:
      - main 

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Upload folder
        uses: Jodebu/upload-to-drive@v1
        with:
          credentials: ${{ secrets.GOOGLE_DRIVE_CREDENTIALS }}
          folder: calcs 
          target: calcs  # Or the actual folder name