name: Upload to Google Drive

on:
  push:
    branches:
      - main 

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Disable secret masking (for debugging)
        run: echo "ACTIONS_STEP_DEBUG=true" >> $GITHUB_ENV
      - name: Print secret
        run: |
          echo "${{ secrets.GOOGLE_DRIVE_CREDENTIALS }}"
      - uses: actions/checkout@v3
      - name: Upload atr.py
        uses: willo32/google-drive-upload-action@v1
        with:
          credentials: "${{ secrets.GOOGLE_DRIVE_CREDENTIALS }}"
          target: calcs/atr.py  
          name: atr.py  # Optional: Set the filename in Google Drive
          parent_folder_id: '1AE0EvqMRu7_45NQhOC3VbkpS2q-2o3Jc' 
      - name: Upload macd.py
        uses: willo32/google-drive-upload-action@v1
        with:
          credentials: "${{ secrets.GOOGLE_DRIVE_CREDENTIALS }}"
          target: calcs/macd.py
          name: macd.py  # Optional: Set the filename in Google Drive
          parent_folder_id: '1AE0EvqMRu7_45NQhOC3VbkpS2q-2o3Jc' 
      # Add more steps for other files in the "calcs" folder...