name: Upload to Google Drive

on:
  push:
    branches:
      - main 

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Enable debugging
        run: |
          echo "${{ secrets.GOOGLE_DRIVE_CREDENTIALS }}" |
          echo "ACTIONS_STEP_DEBUG=true" >> $GITHUB_ENV
      - uses: actions/checkout@v3
      - name: Upload folder
        uses: Jodebu/upload-to-drive@v1
        with:
          credentials: ${{ secrets.GOOGLE_DRIVE_CREDENTIALS }}
          folder: calcs 
          target: 1AE0EvqMRu7_45NQhOC3VbkpS2q-2o3Jc  # Or the actual folder name

